### ISSUE TITLE
The calls on properties

### ISSUE THREAD

**Issue by kleach** [klauer/qtpynodeeditor#48]
These lines:

https://github.com/klauer/qtpynodeeditor/blob/53aac62293345e832cb3a726ed3bd92810476b3d/qtpynodeeditor/node_geometry.py#L356
https://github.com/klauer/qtpynodeeditor/blob/53aac62293345e832cb3a726ed3bd92810476b3d/qtpynodeeditor/node_geometry.py#L378
https://github.com/klauer/qtpynodeeditor/blob/53aac62293345e832cb3a726ed3bd92810476b3d/qtpynodeeditor/node_geometry.py#L381

follow to `TypeError: 'int' object is not callable`

**Comment by klauer** [comment]
Thanks for reporting this 👍  Looks like I've missed a few others, even.
