### ISSUE TITLE
How to add menubar to the window.

### ISSUE THREAD

**Issue by mvrckwong** [klauer/qtpynodeeditor#54]
Hello, I wanted to add menubar (file, edit, help) in the main window or view. 
![image](https://user-images.githubusercontent.com/28927875/198197206-fd352318-43fa-4f44-a827-8f4a20ddfb9e.png)

**Comment by klauer** [comment]
Your question is a Qt (PyQt) question and not a qtpynodeeditor question.

qtpynodeeditor gives you a [`QGraphicsView`](https://github.com/klauer/qtpynodeeditor/blob/8d149c08fdc47cd8e16f550a059b329e810ec850/qtpynodeeditor/examples/calculator.py#L430) in the example which you can embed into larger applications as desired. I'll give you one hint: you might want a [`QMainWindow`](https://doc.qt.io/qt-5/qmainwindow.html) with the flow view as the central widget.
